# infra/docker-compose.yml
version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ../backend/foodgram
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    build: ../frontend
    env_file:
      - .env
    volumes:
      - ../frontend/build:/usr/share/nginx/html/

  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
